channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=24.1.2
- pip:
  - mlflow==2.14.3
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.2.2
  - pyyaml==6.0.1
  - torch==2.3.1
  - torchvision==0.18.1
  - tqdm==4.66.4
name: mlflow-env
