TARGET_COLUMNS: ['X4_mean', 'X11_mean', 'X18_mean', 'X50_mean', 'X26_mean', 'X3112_mean']
N_VAL_SAMPLES: 46
MODEL_NAME: 'efficientnet_b5.sw_in12k_ft_in1k'
V_MIN: 0
V_MAX: 0
TARGET_COLUMNS_TEST: ['X4', 'X11', 'X18', 'X50', 'X26', 'X3112']
BATCH_SIZE: 24
BATCH_SIZE_VAL: 128
LOG_FEATURES: ['X11_mean', 'X18_mean', 'X50_mean', 'X26_mean', 'X3112_mean']
N_TARGETS: 6

IMAGE_SIZE0: 512
IMAGE_SIZE: 288

LR_MAX: 3e-4
WEIGHT_DECAY: 0.01
N_EPOCHS: 12

SEED: 42
EPS: 1e-6